language: node_js
node_js:
  - 16
cache:
  directories:
  - node_modules
script:
  - npm run build
  - npm run export
  - touch out/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 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
  local_dir: out 
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master|main)$